#!/bin/bash

# arcade1up-lcd-marquee; control an LCD in a Arcade1Up marquee.
#
# Please see the file LICENSE.txt in the source's root directory.
#
#  This file written by Ryan C. Gordon.

FULLPATH=`realpath $1`
exec dbus-send --system --type=signal / org.icculus.Arcade1UpMarquee.ShowImage string:"$FULLPATH"

